### ISSUE TITLE
WGLC 1 Feedback from Neil Madden

### ISSUE THREAD

**Issue by OR13** [cose-wg/draft-ietf-cose-dilithium#9]
https://mailarchive.ietf.org/arch/msg/cose/eA2KV31yXVmnF7PwFG4HnvyO5pc/

**Comment by ilaril** [comment]
There is subtle related consideration about the "pub" field in AKP: For some algorithms, it is possible to derive public key from private key, and including both causes possible security issues (e.g., X-Wing bans including public key in private X.509 keys for security reasons). But for others, it is not possible to derive public key from private key, and thus the public key must be present in private keys.

Worst case, inconsistent keys can cause key compromise. Even if Ed25519 and Ed448 are not defined for use with AKP, there is an obvious interpretation for AKP with those algorithms, and for both using inconsistent keys can be instant key compromise (seeing two signatures for the same message with two different public key values exposes the private scalar).

**Comment by OR13** [comment]
Pending a reply to https://mailarchive.ietf.org/arch/msg/spasm/tI0aW10tiDwrzcg_z8U5kNAmkIw/

I plan to set ctx to the empty string for all algorithms registered in this draft.

**Comment by OR13** [comment]
> The test vectors should document what the various fields are (some appear to be hex, others base64), and maybe the step by step computations. I’m also not sure an all-zero private key, and reusing the same key for all algorithms, is necessarily a good way to generate test vectors. 

We will need to ask the lists regarding this, and potentially coordinate with LAMPS

**Comment by OR13** [comment]
Addressed in https://mailarchive.ietf.org/arch/msg/cose/C_FAD4WXBX1GwfziRMHoMVSXjh0/
